// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zshxjnprtwkkoqmmwiwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaHhqbnBydHdra29xbW13aXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA1OTAsImV4cCI6MjA3NDM1NjU5MH0.sCFhZ6UuwhQARiA7UOSCtHzg0wne5KhZGogWECqrlF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});